name = "CliPackages"
uuid = "a73e957c-2eed-4bd2-b375-aa23c2b5088f"
authors = ["xbtry <89214067+xbtry@users.noreply.github.com>"]
version = "0.1.0"
description = "General-purpose CLI package aggregator for Julia. Includes useful tools like ArgParse, PrettyTables, LoggingExtras, and more."

[deps]
ArgParse = "c7e460c6-1ee6-5ef2-bc5e-363e4285f043"
Crayons = "a8cc5b0e-fc63-5ec1-bde2-0fd8f65c187d"
PrettyTables = "08abe8d2-0a4c-5fef-a5ca-f4c7f5a137ac"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
TerminalMenus = "dc548174-15c3-5faf-af27-7997cfbde655"
