name = "CliPackages"
uuid = "a73e957c-2eed-4bd2-b375-aa23c2b5088f"
authors = ["xbtry <89214067+xbtry@users.noreply.github.com>"]
description = "General-purpose CLI package aggregator for Julia. Includes useful tools like ArgParse, PrettyTables, LoggingExtras, and more."
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
TerminalMenus = "dc548174-15c3-5faf-af27-7997cfbde655"

[compat]
ArgParse = "1.2.0"
Crayons = "4.1.1"
PrettyTables = "2.4.0"
ProgressMeter = "1.10.4"
TerminalMenus = "0.1.0"
